/**
 * Produce the single-file executable SPEC §1 requires: one binary with the API,
 * the migrations, and the frontend inside it.
 *
 * `bun build --compile` embeds anything imported with `type: "file"`, so this
 * generates a manifest module importing every file the Vite build emitted, then
 * compiles an entry point that hands the manifest to the static handler. The
 * generated files live under dist/ and are not committed.
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const clientDir = join(repoRoot, "dist", "client");
const standaloneDir = join(repoRoot, "dist", "standalone");
const outfile = process.argv[2] ?? join(repoRoot, "dist", "onsen");

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = join(dir, entry.name);
      return entry.isDirectory() ? walk(full) : [full];
    }),
  );
  return files.flat();
}

console.log("building the client bundle…");
const vite = Bun.spawnSync(["bunx", "vite", "build"], { cwd: repoRoot, stdio: ["ignore", "inherit", "inherit"] });
if (vite.exitCode !== 0) process.exit(vite.exitCode ?? 1);

const files = (await walk(clientDir)).sort();
if (files.length === 0) throw new Error(`no client build found in ${clientDir}`);

await mkdir(standaloneDir, { recursive: true });

const imports: string[] = [];
const entries: string[] = [];
files.forEach((file, index) => {
  const urlPath = "/" + relative(clientDir, file).split(/[\\/]/).join("/");
  const specifier = "../client/" + relative(clientDir, file).split(/[\\/]/).join("/");
  imports.push(`import file${index} from ${JSON.stringify(specifier)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: file${index},`);
});

await writeFile(
  join(standaloneDir, "manifest.ts"),
  `// Generated by scripts/build-standalone.ts — do not edit.\n${imports.join("\n")}\n\nexport const embeddedClient: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
);

await writeFile(
  join(standaloneDir, "entry.ts"),
  `// Generated by scripts/build-standalone.ts — do not edit.\n` +
    `import { embeddedClient } from "./manifest.ts";\n` +
    `import { setEmbeddedClient } from "../../server/static.ts";\n\n` +
    `setEmbeddedClient(embeddedClient);\n` +
    `await import("../../server/index.ts");\n`,
);

console.log(`embedding ${files.length} client files…`);
const compile = Bun.spawnSync(
  ["bun", "build", "--compile", join(standaloneDir, "entry.ts"), "--outfile", outfile],
  { cwd: repoRoot, stdio: ["ignore", "inherit", "inherit"] },
);
if (compile.exitCode !== 0) process.exit(compile.exitCode ?? 1);

console.log(`\nwrote ${outfile}`);
