/**
 * Download the two product typefaces into client/public/fonts and emit a local
 * @font-face stylesheet.
 *
 * The design handoff requires the fonts be bundled rather than hotlinked: this
 * app is self-hosted and expected to run on hardware without reliable outbound
 * internet. Run with `bun run scripts/fetch-fonts.ts`; the output is committed,
 * so this only needs re-running to change weights or subsets.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const GOOGLE_FONTS_CSS =
  "https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500&family=IBM+Plex+Mono:wght@400;500;600&display=swap";

// A roleplay app in English needs latin and latin-ext; the Cyrillic, Greek, and
// Vietnamese subsets Google serves would triple the bundle for no one.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

// Google serves modern woff2 only to a browser user agent.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const outDir = join(import.meta.dir, "..", "client", "public", "fonts");
await mkdir(outDir, { recursive: true });

const css = await (await fetch(GOOGLE_FONTS_CSS, { headers: { "User-Agent": UA } })).text();

// Each @font-face is preceded by a /* subset */ comment.
const blocks = css.split("/*").slice(1);
const kept: string[] = [];

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf("*/")).trim();
  if (!KEEP_SUBSETS.has(subset)) continue;

  const face = block.slice(block.indexOf("*/") + 2);
  const family = /font-family:\s*'([^']+)'/.exec(face)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(face)?.[1];
  const style = /font-style:\s*(\w+)/.exec(face)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(face)?.[1];
  if (!family || !weight || !style || !url) continue;

  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const filename = `${slug}-${weight}${style === "italic" ? "-italic" : ""}-${subset}.woff2`;
  const bytes = await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer();
  await writeFile(join(outDir, filename), new Uint8Array(bytes));

  const unicodeRange = /unicode-range:\s*([^;]+);/.exec(face)?.[1]?.trim();
  kept.push(
    [
      `/* ${family} ${weight}${style === "italic" ? " italic" : ""} — ${subset} */`,
      `@font-face {`,
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      `  font-display: swap;`,
      `  src: url('/fonts/${filename}') format('woff2');`,
      unicodeRange ? `  unicode-range: ${unicodeRange};` : null,
      `}`,
    ]
      .filter((line) => line !== null)
      .join("\n"),
  );
  console.log(`fetched ${filename} (${bytes.byteLength} bytes)`);
}

const header = `/* Generated by scripts/fetch-fonts.ts — do not edit by hand. */\n\n`;
await writeFile(join(outDir, "fonts.css"), header + kept.join("\n\n") + "\n");
console.log(`wrote ${kept.length} @font-face rules`);
